**Github** : https://github.com/OzgurYldrm/AI-ML-Course     
**Youtube** : https://www.youtube.com/@F%C3%BCt%C3%BCrist_AIntelligence

https://tr.wikipedia.org/wiki/Vikipedi:Veritaban%C4%B1_indirme

In [1]:
import pandas as pd
import re
from collections import Counter
import torch
import numpy as np
import random
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", None)

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
device

device(type='cuda')

# Data

In [4]:
df = pd.read_csv("trwiki_random_2000.csv")

In [5]:
df

                                                                    title  \
0                                                         Sedum patrickii
1                                                      Caselle in Pittari
2                                                           Dekan Yaylası
3                                                             Pat O'Brien
4                                             Musée de l'Aventure Peugeot
...                                                                   ...
1995  Vikipedi:Seçkin resim adayları/Plagiomnium affine laminazellen.jpeg
1996                                 Karanlıkta Bir Çığlık (anlam ayrımı)
1997                                          Kategori:Gambiya'daki çevre
1998                               Kategori:Original Memphis Five üyeleri
1999         Modül:Konum haritası/veri/ABD New Jersey Hudson County/belge

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         text
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {{otomatik taksonkutu | italik_başlık = evet | ad = Sedum patrickii | takson = Sedum | tür = patrickii | resim =  | resim_altyazı =  | sıralama =  | üst_sıralama = | aralık_haritası =  | aralık_haritası_altyazı = | durum = NE | durum_sistemi = IUCN3.1 | durum_kaynak =  <!-- | en_genç_fosil =  | en_eski_fosil =  | fosil_kaynak = --> }}  '''''Sedum patrickii''''', ''[[Sedum]]'' cinsine bağlı bir bitki türüdür.<ref name="GBIF">{{Web kaynağı|url=https://www.gbif.org/species/5361975|başlık=GBIF|erişimtarihi=2 Mart 2024|arşivurl=https://web.archive.org/web/20221206211038/https://www.gbif.org/species/5361975|arşivtarihi=6 Aralık 2022|ölüurl=hayır}}</ref>  <!-- ==Taksonomi== '''''{{kopyala:PAGENAME}}''''' türüne bağlı alttürler (2024):  {{div sütunu|colwidth=280px}} × {{div sütunu-son}}  ==Galeri==  --> == Kaynakça == {{kaynakça}}  == Dış bağlantılar == * {{commons-ufak}} * {{Vikitür-ufak}}  {{taksonçubuğu|from=Q17773592}} {{otorite kontrolü}}  [[Kategori:Sedum]] <!-- [[Kategori:tanımlanan taksonlar]] [[Kategori:tarafından adlandırılmış taksonlar]] -->  {{Sedum-taslak}}

# Wiki Markup Temizleme

In [6]:
def wiki_clean(text):
    if pd.isna(text):
        return ""
    text = re.sub(r"#YÖNLENDİRME.*", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"<.*?>", " ", text, flags=re.DOTALL)
    text = re.sub(r"<ref.*?>.*?</ref>", " ", text, flags=re.DOTALL)
    text = re.sub(r"\{\{.*?\}\}", " ", text, flags=re.DOTALL)
    text = re.sub(r"\{\|.*?\|\}", " ", text, flags=re.DOTALL)
    text = re.sub(r"\[\[File:.*?\]\]", " ", text)
    text = re.sub(r"\[\[Dosya:.*?\]\]", " ", text)
    text = re.sub(r"\[\[.*?\|(.*?)\]\]", r"\1", text)
    text = re.sub(r"\[\[.*?\]\]", " ", text)
    text = text.replace("'''", " ")
    text = text.replace("''", " ")
    text = re.sub(r"\|.*?=", " ", text)
    text = re.sub(r"==.*?==", " ", text)
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"\d+", " ", text)
    text = re.sub(r"[^a-zA-ZçğıöşüÇĞİÖŞÜ\s]", " ", text)
    text = text.lower()
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

In [7]:
df["text"] = df["text"].apply(wiki_clean)

In [8]:
df

,title,text
0,Sedum patrickii,sedum patrickii cinsine bağlı bir bitki türüdür
1,Caselle in Pittari,ülke caselle in pittari şehrinin raptiye harita boyutu campania i̇talya px caselle in pittari
2,Dekan Yaylası,
3,Pat O'Brien,müzisyen şarkı sözü yazarı gitar plak şirketi ın albümündeki render my prey adlı şarkının solo gitarında yer aldı de in solo çıkış albümü da yer alan race against disaster da gitardaydı aynı yıl in albümünde solo konuk olarak göründü tutuklanması aralık de ateşli silahla haneye tecavüz ve yaralama nedeniyle hapis cezasına ve ayrıca beş yıl gözetimin yanı sıra dolar para cezasına çarptırıldı mart ta o brien hapis cezasına çarptırıldı ve beş yıl gözetim altında tutulma cezası aldı ayrıca evinde yapılan araştırmada den fazla ateşli silah ve üç kafatası bulundu cannibal corpse ağ sayfası myspace te pat o brien
4,Musée de l'Aventure Peugeot,mus e de l aventure peugeot peugeot ailesi tarafından yılında müze
...,...,...
1995,Vikipedi:Seçkin resim adayları/Plagiomnium affine laminazellen.jpeg,mach iavelli msj mart utc thumb px
1996,Karanlıkta Bir Çığlık (anlam ayrımı),blake edwards ın yönettiği yapımı komedi filmi özgün adı a shot in the dark fred schepisi nin yönettiği yapımı dramatik film özgün adı a cry in the dark olan filmin diğer bir adı da evil angels dır
1997,Kategori:Gambiya'daki çevre,çevre
1998,Kategori:Original Memphis Five üyeleri,
1999,Modül:Konum haritası/veri/ABD New Jersey Hudson County/belge,

# Vocab

In [9]:
df["tokens"] = df["text"].str.split()

In [15]:
all_tokens = [w for doc in df["tokens"] for w in doc]
counter = Counter(all_tokens)

min_count = 5
vocab = {w: c for w, c in counter.items() if c >= min_count}

word2idx = {w: i for i, w in enumerate(vocab.keys())}
idx2word = {i: w for w, i in word2idx.items()}

vocab_size = len(word2idx)
print("Vocab size:", vocab_size)

window_size = 5
n_neg = 5           
max_samples = 200000 # RAM koruma

pairs = []

for doc in df["tokens"]:

    indexed = [word2idx[w] for w in doc if w in word2idx]
    
    for i, center in enumerate(indexed):
        
        start = max(0, i - window_size)
        end = min(len(indexed), i + window_size + 1)
        
        context_words = indexed[start:i] + indexed[i+1:end]
        
        for context in context_words:
            
            pairs.append((center, context, 1))
    
            neg_count = 0
            while neg_count < n_neg:
                
                neg = random.randint(0, vocab_size - 1)
                if neg != context and neg != center:
                    pairs.append((center, neg, 0))
                    neg_count += 1
            
            if len(pairs) >= max_samples:
                break
        
        if len(pairs) >= max_samples:
            break
    
    if len(pairs) >= max_samples:
        break

binary_df = pd.DataFrame(
    pairs,
    columns=["center", "context", "label"]
)

print(binary_df.head())
print("Toplam örnek:", len(binary_df))
print("Positive oranı:", binary_df["label"].mean())

Vocab size: 2202
   center  context  label
0       0        1      1
1       0     1937      0
2       0     1098      0
3       0     1146      0
4       0      130      0
Toplam örnek: 200004
Positive oranı: 0.16666666666666666

# Dataset

In [17]:
class SkipGramDataset(Dataset):
    def __init__(self, dataframe):
        
        self.centers = torch.tensor(
            dataframe["center"].values,
            dtype=torch.long
        )
        
        self.contexts = torch.tensor(
            dataframe["context"].values,
            dtype=torch.long
        )
        
        self.labels = torch.tensor(
            dataframe["label"].values,
            dtype=torch.float32
        )
    
    def __len__(self):
        return len(self.centers)
    
    def __getitem__(self, idx):
        return (
            self.centers[idx],
            self.contexts[idx],
            self.labels[idx]
        )

In [19]:
batch_size = 1024
dataset = SkipGramDataset(binary_df)
loader = DataLoader(
    dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=4,
    pin_memory=True
)

# Model

In [20]:
class SkipGramBinary(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super().__init__()
        self.input_embeddings = nn.Embedding(vocab_size, embedding_dim) # center embedding
        self.output_embeddings = nn.Embedding(vocab_size, embedding_dim) # context embedding
        self._init_embeddings()
    
    
    def _init_embeddings(self): # Word2Vec paper initialization
        initrange = 0.5 / self.input_embeddings.embedding_dim
        self.input_embeddings.weight.data.uniform_(-initrange, initrange)
        self.output_embeddings.weight.data.uniform_(-0, 0)
    
    def forward(self, center, context):
        v = self.input_embeddings(center)     # (B, D)
        u = self.output_embeddings(context)   # (B, D)
        score = torch.sum(v * u, dim=1)       # (B,)
        return score

In [22]:
vocab_size = len(word2idx)
embedding_dim = 300

model = SkipGramBinary(vocab_size, embedding_dim)
model.to(device)
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

# Training

In [23]:
for epoch in range(10):
    total_loss = 0
    for center, context, label in loader:
        center = center.to(device)
        context = context.to(device)
        label = label.to(device)
        optimizer.zero_grad()
        logits = model(center, context)
        loss = criterion(logits, label)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1} Loss: {total_loss/len(loader):.4f}")

Epoch 1 Loss: 0.4715
Epoch 2 Loss: 0.2638
Epoch 3 Loss: 0.2429
Epoch 4 Loss: 0.2272
Epoch 5 Loss: 0.2117
Epoch 6 Loss: 0.1949
Epoch 7 Loss: 0.1773
Epoch 8 Loss: 0.1593
Epoch 9 Loss: 0.1422
Epoch 10 Loss: 0.1266

# Evaluation

In [24]:
def get_embedding(word, model, word2idx, device="cpu"):
    if word not in word2idx:
        raise ValueError(f"{word} vocab içinde yok")
    
    model.eval()
    idx = torch.tensor(
        [word2idx[word]],
        dtype=torch.long,
        device=device
    )
    with torch.no_grad():
        embedding = model.input_embeddings(idx)
    
    return embedding.squeeze(0).cpu()

In [ ]:
vec = get_embedding("ankara", model, word2idx, device)
print(vec.shape)
print(vec)

In [38]:
word2idx

{'cinsine': 0,
 'bağlı': 1,
 'bir': 2,
 'bitki': 3,
 'türüdür': 4,
 'ülke': 5,
 'in': 6,
 'şehrinin': 7,
 'raptiye': 8,
 'harita': 9,
 'boyutu': 10,
 'i̇talya': 11,
 'px': 12,
 'müzisyen': 13,
 'şarkı': 14,
 'yazarı': 15,
 'gitar': 16,
 'şirketi': 17,
 'ın': 18,
 'my': 19,
 'adlı': 20,
 'şarkının': 21,
 'solo': 22,
 'yer': 23,
 'aldı': 24,
 'de': 25,
 'çıkış': 26,
 'albümü': 27,
 'da': 28,
 'alan': 29,
 'aynı': 30,
 'yıl': 31,
 'olarak': 32,
 'aralık': 33,
 've': 34,
 'nedeniyle': 35,
 'ayrıca': 36,
 'beş': 37,
 'yanı': 38,
 'sıra': 39,
 'dolar': 40,
 'para': 41,
 'mart': 42,
 'ta': 43,
 'o': 44,
 'altında': 45,
 'yapılan': 46,
 'den': 47,
 'fazla': 48,
 'üç': 49,
 'bulundu': 50,
 'sayfası': 51,
 'te': 52,
 'e': 53,
 'l': 54,
 'ailesi': 55,
 'tarafından': 56,
 'yılında': 57,
 'ile': 58,
 'olabilir': 59,
 'türkiye': 60,
 'ili': 61,
 'ilçesi': 62,
 'i̇zmir': 63,
 'ilçesine': 64,
 'mahalle': 65,
 'merkez': 66,
 'k': 67,
 'köy': 68,
 'belde': 69,
 'ankara': 70,
 'kütahya': 71,
 'bursa': 72,
 'düzce': 73,
 'manisa': 74,
 'çorum': 75,
 'antalya': 76,
 'tokat': 77,
 'sinop': 78,
 'balıkesir': 79,
 'trabzon': 80,
 'şanlıurfa': 81,
 'el': 82,
 'mardin': 83,
 'orta': 84,
 'diğer': 85,
 'yunanistan': 86,
 'şehir': 87,
 'bulgaristan': 88,
 'i̇ran': 89,
 'doğu': 90,
 'azerbaycan': 91,
 'eyaleti': 92,
 'nin': 93,
 'şimdi': 94,
 'olmayan': 95,
 'nehri': 96,
 'üzerinde': 97,
 'enerji': 98,
 'amacıyla': 99,
 'yılları': 100,
 'arasında': 101,
 'inşa': 102,
 'edilmiş': 103,
 'ilçesinde': 104,
 'bulunan': 105,
 'tcdd': 106,
 'ye': 107,
 'ait': 108,
 'ana': 109,
 'tren': 110,
 'istasyonu': 111,
 'ayrıldı': 112,
 'alternatif': 113,
 'müzik': 114,
 'yapım': 115,
 'ağustos': 116,
 'bitlis': 117,
 'ilinin': 118,
 'köydür': 119,
 'köyün': 120,
 'eski': 121,
 'adı': 122,
 'yılı': 123,
 'kayıtlarında': 124,
 'kökenli': 125,
 'ya': 126,
 'geçmektedir': 127,
 'il': 128,
 'merkezine': 129,
 'nbsp': 130,
 'km': 131,
 'ilçe': 132,
 'uzaklıktadır': 133,
 'olup': 134,
 'numaralı': 135,
 'lik': 136,
 'yoluyla': 137,
 'bağlıdır': 138,
 'ölüm': 139,
 'tarihi': 140,
 'önde': 141,
 'gelen': 142,
 'biri': 143,
 'olan': 144,
 'hughes': 145,
 'un': 146,
 'ler': 147,
 'touch': 148,
 'and': 149,
 'go': 150,
 'you': 151,
 'first': 152,
 'sınırları': 153,
 'yavaş': 154,
 'hareket': 155,
 'eden': 156,
 'sıcak': 157,
 'daki': 158,
 'ilk': 159,
 'çıkışını': 160,
 'john': 161,
 'g': 162,
 'yönettiği': 163,
 'yeni': 164,
 'filminde': 165,
 'le': 166,
 'birlikte': 167,
 'yaptı': 168,
 'tv': 169,
 'filmi': 170,
 'the': 171,
 'la': 172,
 'rol': 173,
 'mini': 174,
 'dizi': 175,
 'return': 176,
 'to': 177,
 'ı': 178,
 'gibi': 179,
 'ara': 180,
 'devam': 181,
 'etti': 182,
 'ların': 183,
 'başında': 184,
 'amerika': 185,
 'birleşik': 186,
 'devletleri': 187,
 'nde': 188,
 'zaman': 189,
 'geçirdi': 190,
 'burada': 191,
 'tıp': 192,
 'doktoru': 193,
 'dr': 194,
 'televizyon': 195,
 'dizisi': 196,
 'life': 197,
 'on': 198,
 'birkaç': 199,
 'ilgi': 200,
 'bölümünde': 201,
 'komutan': 202,
 'oyuncu': 203,
 'avustralya': 204,
 'from': 205,
 'oynadı': 206,
 'bu': 207,
 'yaklaşık': 208,
 'film': 209,
 'komedi': 210,
 'vardı': 211,
 'daha': 212,
 'sonraki': 213,
 'tanrı': 214,
 'açan': 215,
 'adam': 216,
 'süre': 217,
 'bayan': 218,
 'who': 219,
 's': 220,
 'of': 221,
 'virginia': 222,
 'dahil': 223,
 'edildi': 224,
 'henry': 225,
 'annesi': 226,
 'son': 227,
 't': 228,
 'pac': 229,
 'veya': 230,
 'i̇mparatorluğu': 231,
 'doğan': 232,
 'küçük': 233,
 'nın': 234,
 'temmuz': 235,
 'sonra': 236,
 'yı': 237,
 'büyük': 238,
 'taç': 239,
 'tüm': 240,
 'bunlar': 241,
 'hala': 242,
 'ikna': 243,
 'etmek': 244,
 'için': 245,
 'yapıldı': 246,
 'ekim': 247,
 'öldü': 248,
 'onun': 249,
 'yerine': 250,
 'başka': 251,
 'kardeşi': 252,
 'geçti': 253,
 'w': 254,
 'h': 255,
 'history': 256,
 'com': 257,
 'boyu': 258,
 'forma': 259,
 'giymektedir': 260,
 'pasifik': 261,
 'bölgesi': 262,
 'doğal': 263,
 'biridir': 264,
 'bölge': 265,
 'tamamen': 266,
 'ne': 267,
 'biyolojik': 268,
 'açısından': 269,
 'önemli': 270,
 'kabul': 271,
 'edilmektedir': 272,
 'dünyanın': 273,
 'en': 274,
 'yüksek': 275,
 'sahiptir': 276,
 'bölgelerde': 277,
 'yıllık': 278,
 'kadar': 279,
 'familya': 280,
 'evet': 281,
 'etiketlerini': 282,
 'kullanmayın': 283,
 'width': 284,
 'style': 285,
 'colspan': 286,
 'background': 287,
 'd': 288,
 'f': 289,
 'text': 290,
 'align': 291,
 'center': 292,
 'ff': 293,
 'color': 294,
 'top': 295,
 'padding': 296,
 'left': 297,
 'nun': 298,
 'yaptığı': 299,
 'girmiş': 300,
 'dir': 301,
 'hayat': 302,
 'bayram': 303,
 'babası': 304,
 'emin': 305,
 'seçimi': 306,
 'geçen': 307,
 'görev': 308,
 'modern': 309,
 'ayak': 310,
 'genel': 311,
 'aşırı': 312,
 'dolayı': 313,
 'iki': 314,
 'yine': 315,
 'arada': 316,
 'güllü': 317,
 'tayfur': 318,
 'çıkar': 319,
 'yüzünden': 320,
 'çıkan': 321,
 'karar': 322,
 'verir': 323,
 'kendilerini': 324,
 'diye': 325,
 'olduğunu': 326,
 'her': 327,
 'a': 328,
 'olur': 329,
 'ama': 330,
 'başlar': 331,
 'arap': 332,
 'sitesi': 333,
 'onları': 334,
 'araştırma': 335,
 'ortak': 336,
 'akademik': 337,
 'yayınlanan': 338,
 'başarılı': 339,
 'geniş': 340,
 'birincil': 341,
 'alanı': 342,
 'ondan': 343,
 'üzerine': 344,
 'ilgili': 345,
 'astronom': 346,
 'güzel': 347,
 'yan': 348,
 'dedi': 349,
 'bart': 350,
 'astronomi': 351,
 'alanında': 352,
 'derece': 353,
 'popüler': 354,
 'dikkat': 355,
 'kendisi': 356,
 'eşi': 357,
 'uluslararası': 358,
 'birliği': 359,
 'parçası': 360,
 'verdiği': 361,
 'familyasına': 362,
 'tir': 363,
 'mesaj': 364,
 'kasım': 365,
 'utc': 366,
 'varsa': 367,
 'lütfen': 368,
 'eyalet': 369,
 'altbölüm': 370,
 'türü': 371,
 'bilinir': 372,
 'kendi': 373,
 'kuzey': 374,
 'dil': 375,
 'kökeni': 376,
 'altfamilyasına': 377,
 'böcek': 378,
 'idir': 379,
 'değişiklik': 380,
 'yaşayan': 381,
 'insanların': 382,
 'savaşı': 383,
 'sahip': 384,
 'şablon': 385,
 'taşıma': 386,
 'sayfa': 387,
 'koruma': 388,
 'dosyalar': 389,
 'kullanım': 390,
 'geçici': 391,
 'hayvan': 392,
 'haziran': 393,
 'hayır': 394,
 'kategori': 395,
 'otorotasyon': 396,
 'tam': 397,
 'adıyla': 398,
 'otomatik': 399,
 'rotor': 400,
 'motor': 401,
 'boyunca': 402,
 'bugünkü': 403,
 'yaygın': 404,
 'kuyruk': 405,
 'durumunda': 406,
 'uçağı': 407,
 'güvenli': 408,
 'şekilde': 409,
 'yere': 410,
 'yüzden': 411,
 'acil': 412,
 'durum': 413,
 'ortaya': 414,
 'li': 415,
 'ise': 416,
 'herhangi': 417,
 'sistemine': 418,
 'hava': 419,
 'normal': 420,
 'aşağı': 421,
 'doğru': 422,
 'ancak': 423,
 'teknik': 424,
 'yani': 425,
 'az': 426,
 'olduğu': 427,
 'durumlarda': 428,
 'serbest': 429,
 'girer': 430,
 'sırasında': 431,
 'eder': 432,
 'gerçek': 433,
 'sonuç': 434,
 'tek': 435,
 're': 436,
 'i̇l': 437,
 'kent': 438,
 'hans': 439,
 'tungesvik': 440,
 'mayıs': 441,
 'ö': 442,
 'hristiyan': 443,
 'oğlu': 444,
 'üniversitesi': 445,
 'nden': 446,
 'oldu': 447,
 'çalıştı': 448,
 'belediye': 449,
 'meclisi': 450,
 'dan': 451,
 'norveç': 452,
 'na': 453,
 'seçildi': 454,
 'kez': 455,
 'tekrar': 456,
 'm': 457,
 'görevi': 458,
 'ulusal': 459,
 'almaktadır': 460,
 'siyasetçi': 461,
 'meydana': 462,
 'yaşında': 463,
 'abd': 464,
 'etkin': 465,
 'yıllar': 466,
 'günümüz': 467,
 'aşağıdaki': 468,
 'silinmeye': 469,
 'aday': 470,
 'sayfanın': 471,
 'arşivlenmiş': 472,
 'tartışmasıdır': 473,
 'yapmayınız': 474,
 'delete': 475,
 'wpreason': 476,
 'sonucunda': 477,
 'silinmesine': 478,
 'verilmiştir': 479,
 'sil': 480,
 'silinsin': 481,
 'gerekçeye': 482,
 'katılıyorum': 483,
 'mevcut': 484,
 'değil': 485,
 'kadı': 486,
 'hakkında': 487,
 'güvenilir': 488,
 'bağımsız': 489,
 'kaynak': 490,
 'can': 491,
 'yukarıdaki': 492,
 'di̇zi̇nyok': 493,
 'vikipedi': 494,
 'site': 495,
 'üretilen': 496,
 'açık': 497,
 'özgür': 498,
 'temel': 499,
 'kısa': 500,
 'bilgiler': 501,
 'yardımcı': 502,
 'olmak': 503,
 'konusunda': 504,
 'nasıl': 505,
 'arama': 506,
 'kullanılır': 507,
 'listesi': 508,
 'göre': 509,
 'eğer': 510,
 'rağmen': 511,
 'makale': 512,
 'adını': 513,
 'kullanıcı': 514,
 'deneme': 515,
 'tartışma': 516,
 'resim': 517,
 'ismi': 518,
 'yapılır': 519,
 'geri': 520,
 'bazı': 521,
 'şablonları': 522,
 'hazırlanır': 523,
 'edilir': 524,
 'sözlüğü': 525,
 'i̇yi': 526,
 'yazı': 527,
 'kaynaklar': 528,
 'kitabı': 529,
 'projesi': 530,
 'şablonu': 531,
 'oluşturmak': 532,
 'bilgileri': 533,
 'üst': 534,
 'içinde': 535,
 'yeterli': 536,
 'yardım': 537,
 'aktivist': 538,
 'cyril': 539,
 'doğdu': 540,
 'hindistan': 541,
 'hük': 542,
 'meti': 543,
 'dördüncü': 544,
 'sivil': 545,
 'ödülü': 546,
 'nü': 547,
 'kazandı': 548,
 'kutsal': 549,
 'meryem': 550,
 'enstitüsü': 551,
 'nün': 552,
 'loreto': 553,
 'çocuklara': 554,
 'kaliteli': 555,
 'eğitim': 556,
 'kişi': 557,
 'yerleşti': 558,
 'gündüz': 559,
 'okulu': 560,
 'kalküta': 561,
 'müdürü': 562,
 'michael': 563,
 'edebiyat': 564,
 'i̇rlanda': 565,
 'cumhurbaşkanlığı': 566,
 'hizmet': 567,
 'kamu': 568,
 'verilen': 569,
 'yönetim': 570,
 'özel': 571,
 'defa': 572,
 'arkadaşı': 573,
 'yılın': 574,
 'çalışma': 575,
 'grubu': 576,
 'rahibe': 577,
 'sınıf': 578,
 'şu': 579,
 'anda': 580,
 'i': 581,
 'okul': 582,
 'batı': 583,
 'gecekondu': 584,
 'kalan': 585,
 'kast': 586,
 'sosyal': 587,
 'öğrenci': 588,
 'topluluğu': 589,
 'v': 590,
 'üzerindeki': 591,
 'öğrencileri': 592,
 'programında': 593,
 'kırsal': 594,
 'öğretmen': 595,
 'bakınız': 596,
 'önce': 597,
 'çocuğu': 598,
 'adlandırılan': 599,
 'çok': 600,
 'mümkün': 601,
 'sürede': 602,
 'genellikle': 603,
 'kısmı': 604,
 'i̇ngilizce': 605,
 'veren': 606,
 'üzere': 607,
 'öğretmenler': 608,
 'programı': 609,
 'program': 610,
 'genç': 611,
 'erkek': 612,
 'eğitimi': 613,
 'vermektedir': 614,
 'getirdi': 615,
 'sadece': 616,
 'gelir': 617,
 'öğretim': 618,
 'gereksiz': 619,
 'durumda': 620,
 'kentsel': 621,
 'kolu': 622,
 'ediyor': 623,
 'taki': 624,
 'nda': 625,
 'benzer': 626,
 'çocuk': 627,
 'taşıyan': 628,
 'sahibi': 629,
 'gizli': 630,
 'ev': 631,
 'aktif': 632,
 'çeşitli': 633,
 'örneğin': 634,
 'içi': 635,
 'ele': 636,
 'geleneksel': 637,
 'perşembe': 638,
 'vermek': 639,
 'zamanda': 640,
 'proje': 641,
 'başlamıştır': 642,
 'deki': 643,
 'göçmen': 644,
 'çocuklar': 645,
 'ay': 646,
 'nedenle': 647,
 'devlet': 648,
 'komitesi': 649,
 'i̇nsan': 650,
 'hakları': 651,
 'hem': 652,
 'çalışmaları': 653,
 'nüfusunun': 654,
 'kaynakları': 655,
 'ederek': 656,
 'saat': 657,
 'hattı': 658,
 'telefon': 659,
 'sunmaktadır': 660,
 'oluşan': 661,
 'toplam': 662,
 'net': 663,
 'me': 664,
 'cambridge': 665,
 'end': 666,
 'century': 667,
 'university': 668,
 'press': 669,
 'yönlendi̇r': 670,
 'yay': 671,
 'bulunur': 672,
 'dünya': 673,
 'gece': 674,
 'anılır': 675,
 'merkezi': 676,
 'deniz': 677,
 'yaban': 678,
 'yıldız': 679,
 'ngc': 680,
 'avusturya': 681,
 'almanya': 682,
 'belçika': 683,
 'çekoslovakya': 684,
 'fransa': 685,
 'hollanda': 686,
 'i̇ngiltere': 687,
 'i̇spanya': 688,
 'kıbrıs': 689,
 'macaristan': 690,
 'polonya': 691,
 'portekiz': 692,
 'sovyetler': 693,
 'lig': 694,
 'şampiyon': 695,
 'kupası': 696,
 'final': 697,
 'dışı': 698,
 'nadir': 699,
 'erkekler': 700,
 'kg': 701,
 'sırada': 702,
 'katar': 703,
 'şampiyonu': 704,
 'olimpiyat': 705,
 'seçilen': 706,
 'sekiz': 707,
 'temsil': 708,
 'vatandaşı': 709,
 'kaldı': 710,
 'yaz': 711,
 'olimpiyatları': 712,
 'enfeksiyon': 713,
 'tennessee': 714,
 'giren': 715,
 'sinema': 716,
 'i̇ki': 717,
 'kardeş': 718,
 'onlara': 719,
 'kötü': 720,
 'şarkıcısı': 721,
 'fakat': 722,
 'bunu': 723,
 'etmektedir': 724,
 'kendisine': 725,
 'sürekli': 726,
 'resmi': 727,
 'imdb': 728,
 'cins': 729,
 'ürün': 730,
 'bit': 731,
 'b': 732,
 'desteği': 733,
 'online': 734,
 'n': 735,
 'st': 736,
 'almıştır': 737,
 'tarihinde': 738,
 'coğrafi': 739,
 'işaret': 740,
 'camii': 741,
 'eskiden': 742,
 'roma': 743,
 'döneminden': 744,
 'kalma': 745,
 'din': 746,
 'yapıldığı': 747,
 'latin': 748,
 'ciddi': 749,
 'günümüzde': 750,
 'mustafa': 751,
 'paşa': 752,
 'oluşturan': 753,
 'kilise': 754,
 'edilmiştir': 755,
 'muhammed': 756,
 'file': 757,
 'jpg': 758,
 'kaynakça': 759,
 'dış': 760,
 'bağlantılar': 761,
 'ermeni': 762,
 'kanada': 763,
 'doğumlu': 764,
 'aldığı': 765,
 'filmleri': 766,
 'heart': 767,
 'vb': 768,
 'rock': 769,
 'is': 770,
 'c': 771,
 'federal': 772,
 'güney': 773,
 'bölüm': 774,
 'şehrin': 775,
 'nüfusu': 776,
 'itibarı': 777,
 'dır': 778,
 'yes': 779,
 'veri': 780,
 'dik': 781,
 'açıklık': 782,
 'mantar': 783,
 'yeşil': 784,
 'su': 785,
 'faaliyet': 786,
 'çevresindeki': 787,
 'bölgenin': 788,
 'farklı': 789,
 'kullanılan': 790,
 'ndan': 791,
 'yakın': 792,
 'cinsler': 793,
 'iline': 794,
 'yerelnet': 795,
 'border': 796,
 'em': 797,
 'solid': 798,
 'right': 799,
 'hlist': 800,
 'grup': 801,
 'şubat': 802,
 'rapsar': 803,
 'ocak': 804,
 'ileti': 805,
 'by': 806,
 'saint': 807,
 'sainte': 808,
 'sa': 809,
 'val': 810,
 'eylül': 811,
 'çapında': 812,
 'mehmet': 813,
 'türk': 814,
 'tbmm': 815,
 'x': 816,
 'dönem': 817,
 'milletvekilliği': 818,
 'yapmıştır': 819,
 'evli': 820,
 'altı': 821,
 'babasıdır': 822,
 'iken': 823,
 'yılındaki': 824,
 'yasa': 825,
 'değişikliğinden': 826,
 'adana': 827,
 'stadyumu': 828,
 'bulunmaktadır': 829,
 'atatürk': 830,
 'parkı': 831,
 'ikinci': 832,
 'kendini': 833,
 'devletin': 834,
 'ilan': 835,
 'p': 836,
 'muhtemelen': 837,
 'çin': 838,
 'verdi': 839,
 'ülkenin': 840,
 'öldürüldü': 841,
 'bunun': 842,
 'neden': 843,
 'kendine': 844,
 'sonrasında': 845,
 'ten': 846,
 'yoktur': 847,
 'başkan': 848,
 'seyirci': 849,
 'ndaki': 850,
 'suriyeli': 851,
 'mülteciler': 852,
 'bazen': 853,
 'mülteci': 854,
 'krizi': 855,
 'larda': 856,
 'sayıda': 857,
 'geldiği': 858,
 'bölgede': 859,
 'sahipliği': 860,
 'avrupa': 861,
 'ab': 862,
 'yönelik': 863,
 'girdi': 864,
 'üzerinden': 865,
 'milyon': 866,
 'ilişkileri': 867,
 'olmuştur': 868,
 'european': 869,
 'union': 870,
 'turkish': 871,
 'çıkardı': 872,
 'suriye': 873,
 'kurdu': 874,
 'sağlamak': 875,
 'nisan': 876,
 'tarihsel': 877,
 'irak': 878,
 'başladı': 879,
 'savaş': 880,
 'akın': 881,
 'i̇ranlı': 882,
 'book': 883,
 'vol': 884,
 'pp': 885,
 'diasporası': 886,
 'dini': 887,
 'sahipti': 888,
 'beri': 889,
 'pek': 890,
 'üyesi': 891,
 'terk': 892,
 'sık': 893,
 'gitti': 894,
 'general': 895,
 'dönemde': 896,
 'al': 897,
 'page': 898,
 'kürt': 899,
 'insan': 900,
 'baskı': 901,
 'dağlık': 902,
 'ardından': 903,
 'nüfusun': 904,
 'neredeyse': 905,
 'u': 906,
 'savaşın': 907,
 'yıllarında': 908,
 'özellikle': 909,
 'sayısı': 910,
 'ölçüde': 911,
 'itibarıyla': 912,
 'bunlardan': 913,
 'diğerleri': 914,
 'i̇ç': 915,
 'rusya': 916,
 'işgal': 917,
 'yana': 918,
 'ukraynalı': 919,
 'bakanı': 920,
 'kırım': 921,
 'yarışması': 922,
 'asıllı': 923,
 'çıktı': 924,
 'rus': 925,
 'yol': 926,
 'yılına': 927,
 'klasik': 928,
 'tipi': 929,
 'lerin': 930,
 'dışında': 931,
 'ikamet': 932,
 'ekonomik': 933,
 'göç': 934,
 'müdürlüğü': 935,
 'veriler': 936,
 'uzun': 937,
 'olanak': 938,
 'iç': 939,
 'gürcü': 940,
 'kullanarak': 941,
 'i̇stanbul': 942,
 'tarihinin': 943,
 'barış': 944,
 'saldırısı': 945,
 'cumhuriyeti': 946,
 'arasındaki': 947,
 'sınır': 948,
 'bölgesinde': 949,
 'federasyonu': 950,
 'sona': 951,
 'günlük': 952,
 'maruz': 953,
 'olumsuz': 954,
 'güçleri': 955,
 'var': 956,
 'lar': 957,
 'aracılığıyla': 958,
 'toplum': 959,
 'gerektiğini': 960,
 'etmiştir': 961,
 'ilişkin': 962,
 'idari': 963,
 'new': 964,
 'kanun': 965,
 'yasal': 966,
 'sağlık': 967,
 'erişim': 968,
 'this': 969,
 'source': 970,
 'co': 971,
 'with': 972,
 'united': 973,
 'kişilerin': 974,
 'library': 975,
 'adalet': 976,
 'bakanlığı': 977,
 'bünyesinde': 978,
 'kuruldu': 979,
 'kurulmuş': 980,
 'başkanlığı': 981,
 'tarihleri': 982,
 'haline': 983,
 'geldi': 984,
 'karmaşık': 985,
 'hale': 986,
 'res': 987,
 'kurulan': 988,
 'etmeyi': 989,
 'günümüze': 990,
 'bölgeleri': 991,
 'olmaya': 992,
 'ortadan': 993,
 'söyledi': 994,
 'muharebesi': 995,
 'kuzeyinde': 996,
 'i̇slam': 997,
 'devleti': 998,
 'yeniden': 999,
 ...}

In [29]:
vec1 = get_embedding("ankara", model, word2idx, device)
vec2 = get_embedding("istanbul", model, word2idx, device)
vec3 = get_embedding("bitki", model, word2idx, device)

In [31]:
print(np.dot(vec1,vec2))
print(np.dot(vec1,vec3))

-0.0047788993
12.14783

/tmp/ipykernel_5541/22616535.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  print(np.dot(vec1,vec2))
/tmp/ipykernel_5541/22616535.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  print(np.dot(vec1,vec3))